# Generated by Django 4.1.7 on 2023-03-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100)),
                ("thumbnail", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="images")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "statuse",
                    models.CharField(
                        choices=[("d", "Draft"), ("p", "Published")], max_length=1
                    ),
                ),
                ("category", models.ManyToManyField(to="BlogArticle.category")),
            ],
        ),
    ]
