# Generated by Django 4.1.7 on 2023-03-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogArticle", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(),
        ),
    ]
