# Generated by Django 4.1.7 on 2023-03-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BlogArticle", "0005_alter_user_age"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserArticle",
        ),
    ]
